# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-29 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_user4report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltask4group',
            name='project_loc',
            field=models.CharField(max_length=300, verbose_name='project_loc'),
        ),
        migrations.AlterField(
            model_name='alltask4group',
            name='ptn_name',
            field=models.CharField(max_length=100, verbose_name='ptn_file_name'),
        ),
        migrations.AlterField(
            model_name='alltask4user',
            name='project_loc',
            field=models.CharField(max_length=300, verbose_name='project_loc'),
        ),
        migrations.AlterField(
            model_name='alltask4user',
            name='ptn_name',
            field=models.CharField(max_length=100, verbose_name='ptn_file_name'),
        ),
        migrations.AlterField(
            model_name='au4pj',
            name='pj_name',
            field=models.CharField(max_length=300, verbose_name='project_name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=100, verbose_name='group_name'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='notes',
            field=models.CharField(max_length=1000, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project_loc',
            field=models.CharField(max_length=300, verbose_name='project_loc'),
        ),
        migrations.AlterField(
            model_name='task',
            name='ptn_name',
            field=models.CharField(default='mul5', max_length=100, verbose_name='ptn_file_name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='report_file',
            field=models.CharField(default='xxx', max_length=300, verbose_name='report_file'),
        ),
        migrations.AlterField(
            model_name='task_db',
            name='project_loc',
            field=models.CharField(max_length=300, verbose_name='project_loc'),
        ),
        migrations.AlterField(
            model_name='task_db',
            name='ptn_name',
            field=models.CharField(max_length=100, verbose_name='ptn_file_name'),
        ),
        migrations.AlterField(
            model_name='task_db',
            name='report_file',
            field=models.CharField(default='xxx', max_length=300, verbose_name='report_file'),
        ),
        migrations.AlterField(
            model_name='user4report',
            name='report_file',
            field=models.CharField(default='xxx', max_length=300, verbose_name='report_file2'),
        ),
        migrations.AlterField(
            model_name='user4serving',
            name='report_file',
            field=models.CharField(default='xxx', max_length=300, verbose_name='report_file'),
        ),
        migrations.AlterField(
            model_name='user_in_queue',
            name='report_file',
            field=models.CharField(default='xxx', max_length=300, verbose_name='report_file'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=300, null=True, verbose_name='email'),
        ),
    ]
